kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: lxd-csi-controller
  name: lxd-csi-controller
  namespace: lxd-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lxd-csi-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: lxd-csi-controller
    spec:
      serviceAccountName: lxd-csi-controller-sa
      priorityClassName: system-cluster-critical
      nodeSelector:
        kubernetes.io/os: linux
      # Deploy controller only to the control plane nodes.
      # Use affinity instead of nodeSelector as some Kubernetes
      # flavors use label values while others leave it empty.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/controlplane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        # Provisions volumes by calling CreateVolume and DeleteVolume
        # functions of CSI drivers.
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.2
          imagePullPolicy: IfNotPresent
          args:
            - -v=2
            - --csi-address=$(CSI_ADDRESS)
            - --feature-gates=Topology=true
            - --extra-create-metadata
            - --timeout=1200s
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        # Attaches/detaches volumes to/from nodes by calling ControllerPublish
        # and ControllerUnpublish functions of CSI drivers.
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.8.0
          imagePullPolicy: IfNotPresent
          args:
            - "-v=2"
            - "--csi-address=$(CSI_ADDRESS)"
            - "--timeout=1200s"
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        # Resizes volumes by calling ControllerExpandVolume functions of CSI driver
        # when user requests more storage for a PVC.
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.14.0
          imagePullPolicy: IfNotPresent
          args:
            - -v=2
            - --csi-address=$(CSI_ADDRESS)
            - --timeout=1200s
            - --leader-election
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            capabilities:
              drop:
                - ALL
        # Liveness probe for the CSI controller.
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
            - --csi-address=$(CSI_ADDRESS)
            - --http-endpoint=127.0.0.1:39008
            - --probe-timeout=3s
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        # CSI controller.
        - name: lxd-csi-controller
          image: ghcr.io/canonical/lxd-csi-driver:latest-edge
          imagePullPolicy: IfNotPresent
          args:
            - "--node-id=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--devlxd-endpoint=$(DEVLXD_ENDPOINT)"
            - "--controller"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DEVLXD_ENDPOINT
              value: unix:///dev/lxd/sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: devlxd-socket
              mountPath: /dev/lxd/sock
            - name: lxd-csi-secret
              mountPath: /etc/lxd-csi-driver
              readOnly: true
          livenessProbe:
            httpGet:
              host: localhost
              path: /healthz
              port: 39008
            failureThreshold: 3
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
      volumes:
        - name: lxd-csi-secret
          secret:
            secretName: lxd-csi-secret
        - name: devlxd-socket
          hostPath:
            path: /dev/lxd/sock
            type: Socket
        - name: socket-dir
          emptyDir: {}
