name: Tests
on:
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  code-tests:
    if: ${{ github.event_name != 'schedule' || github.repository == 'canonical/lxd-csi-driver' }}
    name: Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0

      - name: Go unit tests
        run: |
          set -eux
          BAD_FORMAT="$(gofmt -s -d .)"
          if [ -n "${BAD_FORMAT}" ]; then
            echo "Formatting issues found in Go file(s):"
            echo "${BAD_FORMAT}"
            exit 1
          fi
          go test -cover ./internal/...

      - name: Helm unit tests
        run: |
          make install-helm
          helm unittest charts/
